name: spider

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  workflow_dispatch:

jobs:
  spider:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      NODE_VERSION: '3.9'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.NODE_VERSION }}

      - name: Setup Python package
        run: pip install -r ./py_news/requirements.txt

      - name: Run spider en bbc news
        run: python ./py_news/bbc.py

      - name: Run spider au abc news
        run: python ./py_news/au_abc.py

      - name: Run spider us newsweek news
        run: python ./py_news/us_newsweek.py

      - name: Run spider us nytimes news
        run: python ./py_news/us_nytimes.py

      - name: Run spider cbsnews news
        run: python ./py_news/cbsnews.py

      - name: Run spider rnz news
        run: python ./py_news/rnz.py

      - name: Run spider aljazeera news
        run: python ./py_news/run.py






